name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies and test (Client)
      working-directory: ./client
      run: |
        npm ci

    - name: Install dependencies and test (Server)
      working-directory: ./server
      run: |
        npm ci
        npm test

    - name: Build Docker images
      run: |
        docker-compose build

