name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies and test (Client)
      working-directory: ./client
      run: |
        npm ci

    - name: Install dependencies and test (Server)
      working-directory: ./server
      run: |
        npm ci
        npm test

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build and push Client Docker image
      run: |
        docker build -t najash01/client-app:latest -f ./client/Dockerfile ./client
        docker push najash01/client-app:latest

    - name: Build and push Server Docker image
      run: |
        docker build -t najash01/server-app:latest -f ./server/Dockerfile ./server
        docker push najash01/server-app:latest

    - name: Deploy on AWS EC2
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem
        ssh -i ec2_ssh_key.pem -o StrictHostKeyChecking=no ec2-user@3.138.189.215 "./deploy_script.sh"
